### ISSUE TITLE
Highlight members that need changing, and highlight option they need changing to rather than using overlay.

### ISSUE THREAD

**Issue by bluelightzero** [simbleau/clan-roster-purifier#8]
You may have tried this, but if not I would be happy to help write this feature for my clan.

**Comment by simbleau** [comment]
Go for it, @bluelightzero . I don't have a reason to maintain this currently. It might be broken right now.

**Comment by bluelightzero** [comment]
It's coming along quite well. Just finishing up bug fixes.

![image](https://user-images.githubusercontent.com/4492982/108222102-62822f80-7130-11eb-99bd-2e3f40a682df.png)

![image](https://user-images.githubusercontent.com/4492982/108222188-74fc6900-7130-11eb-8664-60fd80830418.png)

![image](https://user-images.githubusercontent.com/4492982/108222243-804f9480-7130-11eb-864b-5b0fc30c543e.png)

If you don't want to maintain this plugin any more, I will be happy to take over, just need to let them know on the runelite discord.

I will be adding a few other features in future to do with ignore lists.

**Comment by simbleau** [comment]
Looks excellent! This is definitely a better solution than I originally created.

This was the first plugin I ever made, I am better with RL plugins now, which is good. I still had plans one day to fix it, so I won't be giving it up, but you'll find I'm able to review your code very quickly. You can also message me on Discord: Nuzz#2020.

Originally, this was made with a fully featured discord bot which managed the clan roster and awards event points and things of that nature. I even had a website built for the clan at https://champs.chat

**Comment by bluelightzero** [comment]
Names with correct ranks show up in green.
Names with wrong ranks show up in red.
Names that should be removed show up in black.

**Comment by simbleau** [comment]
@bluelightzero I merged your changes. You'll need to submit a PR to the plugin hub though. ;-) Thanks for the contribution!

**Comment by bluelightzero** [comment]
Thanks @simbleau :)

Changes are on the plugin hub now.
